apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flowforge
resources:
- ../../base
- postgres.yaml
- redis.yaml
- kafka.yaml
secretGenerator:
- name: flowforge-secrets
  literals:
  - DB_PASSWORD=flowforge-local-only
generatorOptions:
  disableNameSuffixHash: true
