apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: scheduler
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scheduler
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: worker
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: worker
