apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flowforge
resources:
- namespace.yaml
- config.yaml
- api.yaml
- scheduler.yaml
- worker.yaml
- frontend.yaml
- worker-hpa.yaml
- disruption-budgets.yaml
